---
# - name: Add Postgres 14 repo
#   shell: |
#     yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
#   args:
#     warn: no

- name: Install postgresql
  yum:
    name:
      - postgresql14-server
      - postgresql14-contrib
  notify:
    - Enable Postgresql

- name : check ThreatIDR directory
  stat:
    path: /var/lib/pgsql/14/data
  register: postgres_data_location

- name: Initialize the PostgreSQL database
  shell: |
    /usr/pgsql-14/bin/postgresql-14-setup initdb # work for condition
  when: not postgres_data_location.stat.exists

- name: Ensure PostgreSQL is listening on *
  lineinfile:
    dest: /var/lib/pgsql/14/data/postgresql.conf
    regexp: '^listen_addresses\s*='
    line: "listen_addresses='*'"
    state: present
  notify: Restart Postgresql

- name: Add new configuration to "pg_hba.conf"
  blockinfile:
    dest: /var/lib/pgsql/14/data/pg_hba.conf
    block: |
      host    all             all             0.0.0.0/0                md5
      host    all             all             ::/0                     md5
  notify: Restart Postgresql

- name: Change peer identification to trust
  shell: /bin/sed -i '/^local/s/peer/trust/' /var/lib/pgsql/14/data/pg_hba.conf
  args:
    warn: no
  notify: Restart Postgresql

- name: Start Postgresql server
  systemd:
    name: postgresql-14
    state: started
  notify:
    - Enable Postgresql

- name: "Create app database"
  postgresql_db:
    state: present
    name: "{{ db_name }}"
  become: yes
  become_user: postgres


- name: "Create db user"
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: yes
  become_user: postgres

- name: "Grant db user access to app db"
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: no
    privs: all
  become: yes
  become_user: postgres