- name: timescaledb | add GPG signing key
  become: true
  rpm_key:
    key: "https://packagecloud.io/timescale/timescaledb/gpgkey"
    state: present
    validate_certs: true
  tags: install

- name: Add Postgres 14 repo
  shell: |
    tee /etc/yum.repos.d/timescale_timescaledb.repo <<EOL
    [timescale_timescaledb]
    name=timescale_timescaledb
    baseurl=https://packagecloud.io/timescale/timescaledb/el/$(rpm -E %{rhel})/\$basearch
    repo_gpgcheck=1
    gpgcheck=0
    enabled=1
    gpgkey=https://packagecloud.io/timescale/timescaledb/gpgkey
    sslverify=1
    sslcacert=/etc/pki/tls/certs/ca-bundle.crt
    metadata_expire=300
    EOL
  args:
    warn: no    
  register: timescaledb_repo


- name: timescaledb | udpate cache
  become: true
  when: timescaledb_repo.changed
  yum:
    update_cache: true
  tags: install

- name: timescaledb | establish dependencies
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ timescaledb_dependencies }}"
  tags: install

- name: timescaledb | configure timescaledb 
  become: true
  command: "timescaledb-tune --quiet --yes --pg-config=/usr/pgsql-14/bin/pg_config"
  tags: configure

- name: timescaledb | restart postgresql
  become: true
  service:
    name: postgresql-14
    state: restarted

- name: timescaledb | add timescaledb extension to postgresql database
  become: true
  become_user: "{{ timescaledb_database_user }}"
  command: 'psql -d {{ timescaledb_database_name }} -c "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;"'
  register: output