---
- name: Install git 
  yum:
    name: git 
    state: present
  become: yes

- name: Check version
  shell: git --version

- name : check ThreatIDR directory
  stat:
    path: /usr/share/nginx/html/threatidr
  register: threadidr_location

- name: TIDR repo exist
  shell: cd /usr/share/nginx/html/threatidr && git branch && git fetch
  when: threadidr_location.stat.exists

- name: TIDR repo not exist
  shell: cd /usr/share/nginx/html/ && git clone https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/pipelinelabo/threatidr.git && cd threatidr && git branch && git fetch
  when: not threadidr_location.stat.exists

- name : Check ThreatIDR directory
  stat:
    path: /usr/share/nginx/html/threatidr/src/static/uploads
  register: threadidr_upload

- name: ThreatIDR make directory UPLOAD 
  command: chdir=/usr/share/nginx/html/threatidr/src/static {{ item }}
  with_items:
  - mkdir uploads
  - cd uploads
  when: not threadidr_upload.stat.exists

- name: ThreatIDR make directory USERS 
  command: chdir=/usr/share/nginx/html/threatidr/src/static/uploads {{ item }}
  with_items:
  - mkdir users
  when: not threadidr_upload.stat.exists













