---
# - name: Install git 
#   yum:
#     name: git 
#     state: present
#   become: yes

# - name: Check version
#   shell: git --version

- name : check ThreatIDR directory
  stat:
    path: /usr/share/nginx/html/threatidr
  register: threadidr_location

- name: TIDR repo exist
  shell: cd /usr/share/nginx/html/threatidr && git branch && git fetch
  when: threadidr_location.stat.exists

- name: TIDR repo not exist
  shell: cd /usr/share/nginx/html/ && git clone https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/pipelinelabo/threatidr.git && cd threatidr && git branch && git fetch
  when: not threadidr_location.stat.exists

- name : Check ThreatIDR directory
  stat:
    path: /usr/share/nginx/html/threatidr/src/static/uploads
  register: threadidr_upload

- name: ThreatIDR make directory UPLOAD 
  command: chdir=/usr/share/nginx/html/threatidr/src/static {{ item }}
  with_items:
  - mkdir uploads
  - cd uploads
  when: not threadidr_upload.stat.exists

- name: ThreatIDR make directory USERS 
  command: chdir=/usr/share/nginx/html/threatidr/src/static/uploads {{ item }}
  with_items:
  - mkdir users
  when: not threadidr_upload.stat.exists

- name: ThreatIDR .env prepare 
  command: chdir=/usr/share/nginx/html/threatidr {{ item }}
  with_items:
  - cp .env.example .env
  when: threadidr_location.stat.exists

- name: Replace  DATABASE_URL line in .env file
  lineinfile:
    path: /usr/share/nginx/html/threatidr/.env
    search_string: 'DATABASE_URL'
    line: DATABASE_URL=postgresql+psycopg2://{{db_user}}:{{db_password}}@localhost/{{db_name}}
    owner: root
    group: root
    mode: '0644'

- name: Replace WHOIS_XML_API_KEY line in .env file
  lineinfile:
    path: /usr/share/nginx/html/threatidr/.env
    search_string: 'WHOIS_XML_API_KEY'
    line: WHOIS_XML_API_KEY={{ WHOIS_XML_API_KEY }}
    owner: root
    group: root
    mode: '0644'

- name: Replace VIRUS_TOTAL_API_KEY line in .env file
  lineinfile:
    path: /usr/share/nginx/html/threatidr/.env
    search_string: 'VIRUS_TOTAL_API_KEY'
    line: VIRUS_TOTAL_API_KEY={{ VIRUS_TOTAL_API_KEY }}
    owner: root
    group: root
    mode: '0644'

- name: ThreatIDR Install pipenv
  shell: pip3 install pipenv

- name: ThreatIDR pipenv intregation process
  command: chdir=/usr/share/nginx/html/threatidr/ {{ item }}
  with_items:
  - pipenv install
  - pip3 install -r requirements.txt
  - npm install
  when: threadidr_location.stat.exists











